stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: smi-master:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: registry.lappis.rocks

- name: Deploy Staging
  when:
    branch: rancher-deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/staging/deployment-master.yaml

branch:
  include: [ master, development, rancher-deploy ]
notification: {}