version: '3.5'

services:
    master:
        container_name: master
        build: .
        env_file: dev-env
        command: ["sh", "scripts/start.sh"]
        ports:
            - 8001:8001
        volumes:
            - .:/smi-master
        depends_on:
            - db

    db:
        container_name: postgres_master
        image: postgres:9.6
        ports:
            - 8008:8008
        env_file: dev-env
        volumes:
            - master-pg-data:/var/lib/postgresql/data

volumes:
    master-pg-data: {}
